import {doc, Timestamp} from 'firebase/firestore';
import {db} from "./plugins/firestore";
import raw from "raw.macro";

console.log(db);

export const nodes = {
    "1": {
        "author_name": "Uncle Sam",
        "content": raw('../code-gallery/1.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1.mp4?alt=media",
        "description": "Is it a circle? Is it a ball? Is it a disc? Be creative and give it a new life.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 0, 0, 0)),
        "view_count": 64,
        "dx": 0,
        "dy": 0,
        "children": [
            doc(db, '/projects/1/nodes/2'),
            doc(db, '/projects/1/nodes/3'),
            doc(db, '/projects/1/nodes/4'),
            doc(db, '/projects/1/nodes/5'),
            doc(db, '/projects/1/nodes/6'),
            doc(db, '/projects/1/nodes/7'),
        ],
    },
    "2": {
        "author_name": "Ben",
        "content": raw('../code-gallery/1_2.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_2.mp4?alt=media",
        "description": "A circle is evolved from a polygon with unlimited sides.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 7, 0, 0)),
        "view_count": 40,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
    },
    "3": {
        "author_name": "Yip",
        "content": raw('../code-gallery/1_3.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_3.mp4?alt=media",
        "description": "A circle is evolved from a polygon with unlimited sides.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 7, 37, 0)),
        "view_count": 72,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
        "children": [
            doc(db, '/projects/1/nodes/8'),
        ],
    },
    "4": {
        "author_name": "ChiChi",
        "content": raw('../code-gallery/1_4.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4.mp4?alt=media",
        "description": "It's alive! It's breathing...",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 8, 32, 0)),
        "view_count": 84,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
        "children": [
            doc(db, '/projects/1/nodes/11'),
            doc(db, '/projects/1/nodes/12'),
            doc(db, '/projects/1/nodes/13'),
        ],
    },
    "5": {
        "author_name": "Tiffany",
        "content": raw('../code-gallery/1_5.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_5.mp4?alt=media",
        "description": "Why don't we make it 3D?!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 9, 47, 0)),
        "view_count": 52,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
        "children": [
            doc(db, '/projects/1/nodes/9'),
        ],
    },
    "6": {
        "author_name": "Dickson",
        "content": raw('../code-gallery/1_6.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_6.mp4?alt=media",
        "description": "Hide and seek!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 17, 47, 0)),
        "view_count": 42,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
    },
    "7": {
        "author_name": "Anthony",
        "content": raw('../code-gallery/1_7.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_7.mp4?alt=media",
        "description": "It's a moon.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 11, 14, 22, 0)),
        "view_count": 72,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/1'),
    },
    "8": {
        "author_name": "Yip",
        "content": raw('../code-gallery/1_3_8.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_3_8.mp4?alt=media",
        "description": "Bouncing...",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 6, 22, 0)),
        "view_count": 56,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/3'),
    },
    "9": {
        "author_name": "Tat",
        "content": raw('../code-gallery/1_5_9.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_5_9.mp4?alt=media",
        "description": "It can follow the sine curve to move",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 2, 8, 0)),
        "view_count": 94,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/5'),
        "children": [
            doc(db, '/projects/1/nodes/10'),
        ],
    },
    "10": {
        "author_name": "Eddie",
        "content": raw('../code-gallery/1_5_9_10.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_5_9_10.mp4?alt=media",
        "description": "Combining sine curves to make it more stunning!!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 19, 47, 0)),
        "view_count": 64,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/9'),
    },
    "11": {
        "author_name": "Yip",
        "content": raw('../code-gallery/1_4_11.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_11.mp4?alt=media",
        "description": "Let's make it colourful!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 19, 47, 0)),
        "view_count": 72,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/4'),
        "children": [
            doc(db, '/projects/1/nodes/14'),
            doc(db, '/projects/1/nodes/19'),
        ],
    },
    "12": {
        "author_name": "Anthony",
        "content": raw('../code-gallery/1_4_12.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_12.mp4?alt=media",
        "description": "It's a rainy day",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 2, 12, 0)),
        "view_count": 44,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/4'),
    },
    "13": {
        "author_name": "Anthony",
        "content": raw('../code-gallery/1_4_13.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13.mp4?alt=media",
        "description": "Is it a face?",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 12, 11, 17, 0)),
        "view_count": 90,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/4'),
        "children": [
            doc(db, '/projects/1/nodes/15'),
            doc(db, '/projects/1/nodes/16'),
        ],
    },
    "14": {
        "author_name": "David",
        "content": raw('../code-gallery/1_4_11_14.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_11_14.mp4?alt=media",
        "description": "Perhaps we can try something different!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 21, 56, 0)),
        "view_count": 36,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/11'),
    },
    "15": {
        "author_name": "Will",
        "content": raw('../code-gallery/1_4_13_15.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13_15.mp4?alt=media",
        "description": "Woo hoo!!! Let's dance!",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 1, 42, 0)),
        "view_count": 148,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/13'),
        "children": [
            doc(db, '/projects/1/nodes/17'),
            doc(db, '/projects/1/nodes/18'),
            doc(db, '/projects/1/nodes/20'),
        ],
    },
    "16": {
        "author_name": "Casper",
        "content": raw('../code-gallery/1_4_13_16.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13_16.mp4?alt=media",
        "description": "Just make it a little bit different.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 8, 27, 0)),
        "view_count": 44,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/13'),
    },
    "17": {
        "author_name": "Casper",
        "content": raw('../code-gallery/1_4_13_15_17.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13_15_17.mp4?alt=media",
        "description": "Just make it a little bit different.",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 20, 35, 0)),
        "view_count": 50,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/15'),
    },
    "18": {
        "author_name": "David",
        "content": raw('../code-gallery/1_4_13_15_18.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13_15_18.mp4?alt=media",
        "description": "He is not dancing, right?",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 22, 35, 0)),
        "view_count": 92,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/15'),
    },
    "19": {
        "author_name": "Che-Yu Wu",
        "content": raw('../code-gallery/1_4_11_19.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_11_19.mp4?alt=media",
        "description": "Isn't it fascinating?",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 11, 35, 0)),
        "view_count": 92,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/11'),
    },
    "20": {
        "author_name": "Anthony",
        "content": raw('../code-gallery/1_4_13_15_20.js'),
        "cover_url": "https://firebasestorage.googleapis.com/v0/b/polyusd-chaining.appspot.com/o/cover%2F1_4_13_15_20.mp4?alt=media",
        "description": "Good bye, little man~",
        "post_time": Timestamp.fromDate(new Date(2022, 6, 13, 5, 35, 0)),
        "view_count": 38,
        "dx": 0,
        "dy": 0,
        "parent": doc(db, '/projects/1/nodes/15'),
    },
};
